[general]
cpus = 16
editor = "/usr/bin/nvim"
doas = false
language = "en-US"

[aur]
build = "/home/nick/.cache/aura/builds"
cache = "/home/nick/.cache/aura/cache"
clones = "/home/nick/.cache/aura/packages"
hashes = "/home/nick/.cache/aura/hashes"
chroot = []
ignores = []
git = false
hotedit = false
shellcheck = true
diff = false
delmakedeps = false
clean = false
warn_unknowns = true
noconfirm = false
nocheck = false
skipdepcheck = false
reverse = false

[backups]
snapshots = "/home/nick/.cache/aura/snapshots"
automatic = true

